name = "esm-prequal-server"
main = "src/index.ts"
compatibility_date = "2025-12-01"

[[d1_databases]]
binding = "DB"
database_name = "esm-prequal-db"
database_id = "fa9278ce-9675-4405-b98f-cc87fbef9aec"
migrations_dir = "migrations"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = false
head_sampling_rate = 1
persist = false
invocation_logs = true

[observability.traces]
enabled = false
persist = false
head_sampling_rate = 1